version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: backoffice_rabbitmq
    ports:
      - "5672:5672"    # Puerto AMQP
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:

