from enum import Enum

class UserRole(str, Enum):
    DOCENTE = "DOCENTE"
    ALUMNO = "ALUMNO"
    ADMIN_IT = "ADMIN_IT"
    ADMIN_A = "ADMIN_A"

class UserState(str, Enum):
    ACTIVO = "ACTIVO"
    INACTIVO = "INACTIVO"
    SUSPENDIDO = "SUSPENDIDO"
    

class Position(str, Enum):
    PROFESOR_TITULAR = "PROFESOR_TITULAR"
    PROFESOR_ADJUNTO = "PROFESOR_ADJUNTO"
    PROFESOR_AUXILIAR = "PROFESOR_AUXILIAR"
    AYUDANTE_CATEDRA = "AYUDANTE_CATEDRA"
    ADMINISTRATIVO = "ADMINISTRATIVO"
    COORDINADOR = "COORDINADOR"
    DIRECTOR = "DIRECTOR"

class DayOfWeek(str, Enum):
    LUNES = "LUNES"
    MARTES = "MARTES"
    MIERCOLES = "MIERCOLES"
    JUEVES = "JUEVES"
    VIERNES = "VIERNES"
    SABADO = "SABADO"
    DOMINGO = "DOMINGO"

class EvaluationType(str, Enum):
    PARCIAL = "PARCIAL"
    FINAL = "FINAL"
    RECUPERATORIO = "RECUPERATORIO"
    TRABAJO_PRACTICO = "TRABAJO_PRACTICO"
    PROYECTO = "PROYECTO"
    EXAMEN_ORAL = "EXAMEN_ORAL"
    QUIZ = "QUIZ"